server:
  port: 8080

spring:
  application:
    name: user-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mariadb://localhost:3306/JPA_N+1_ISSUE
    username: root
    password: 6548
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  logging:
    level:
      org:
        hibernate:
          SQL: TRACE

jwt:
  granted: Bearer
  header: Authorization
  secret: asdasd312321312321321e3lk12l3qs;djq2lk4jqwlkejklqw@@ewqke21;l#
  expiration:
    access: 3600000 # 3600 * 1000
    refresh: 86400000 # 3600 * 24 * 1000